### ISSUE TITLE
Sometimes two direct-bookmark links are added

### ISSUE THREAD

**Issue by 75th** [75th/mario-maker-linker#11] opened 2016-01-10 21:47 UTC
Tested v0.5 in Kiwi IRC, and it worked, but there were two + links next to the generated link. Haven't looked any further into this yet.

**Comment by freundTech** [comment] 2016-01-11 19:29
Can't seem to reproduce it (At least in Firefox. Can't test chrome because of #15).

It has to be either a race condition or  difference with the DOMListener in Chrome. Can you inspect element and copy the page code when it happens the next time?

**Comment by freundTech** [comment] 2016-01-13 07:47
Should be fixed on dev. Needs some testing.

If it works it can be merged into master and the issue can be closed.

EDIT: Couldn't reproduce it after I wrote the fix, but now it's happening again :/

**Comment by freundTech** [comment] 2016-02-01 15:30
This should now be fixed. Issue can be closed if it is confirmed to work in chrome.

**Comment by freundTech** [comment] 2017-11-29 20:23
No activity in almost 2 years. Probably fixed.

**Closed as completed by freundTech** 2017-11-29 20:23 UTC
Labels: bug, waiting for reply
